# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run loadData.py
on:
  schedule:
    - cron: '0 */1***'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout repo content
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
        
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
        pip install urllib

    - name: execute py script
      run: |
        env: 
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run:
          python loadData.py
          
    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
        
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
